### ISSUE TITLE
"Background" is misspelled, bug

### ISSUE THREAD

**Issue by ghost** [Autofirejm/Scratch-Empires#1]
https://github.com/Autofirejm/Scratch-Empires/blob/f0b3c5b845e41a5a7746a5ff88a3095ee124ec43/index.html#L6 Line 6 says `Backgorund-image` but should be `background-image`. Possible mistake?

**Comment by NaincyKumariKnoldus** [comment]
Hey @ILOVETOMAKESTUFF I have fixed this. I have raised a PR for this. Please Review this.
Thanks!

**Comment by Autofirejm** [comment]
Ok thanks for this, you will be invited to help, I’m still kinda new

**Comment by NaincyKumariKnoldus** [comment]
Hey @Autofirejm and @ILOVETOMAKESTUFF You have not  reviewed my PR.

**Comment by ghost** [comment]
@NaincyKumariKnoldus, it was still misspelled. Perhaps you might want to change something before asking for a review?
